-- История действий над составом (#16). Пишется сервисами в момент изменения, а не из тел запросов:
-- только там известно и старое состояние, и имена, из которых складывается читаемая строка.
-- Внешних ключей намеренно нет: запись переживает то, о чём рассказывает (команду распустили,
-- студента удалили), и должна читаться так же, как в день события — поэтому имена скопированы.
CREATE TABLE activity_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action text NOT NULL,
    actor_user_id bigint,
    actor_name text,
    actor_email text,
    track_id bigint,
    team_id bigint,
    related_team_id bigint,
    student_id bigint,
    summary text NOT NULL,
    created_at timestamp without time zone NOT NULL
);

CREATE INDEX activity_log_created_at_idx ON activity_log (created_at DESC);
CREATE INDEX activity_log_team_idx ON activity_log (team_id);
CREATE INDEX activity_log_student_idx ON activity_log (student_id);
